const camposAutomationExercise = {
	loginEmail: '[data-qa="login-email"]',
	loginPassword: '[data-qa="login-password"]',
	loginButton: '[data-qa="login-button"]',
	logoutLink: 'a[href="/logout"]',
	deleteAccountLink: 'a[href="/delete_account"]',
	userIcon: 'a:has(.fa.fa-user)',
	loginErrorMessage: 'p[style*="color: red"]',
	requiredLoginField: '[data-qa="login-email"]:invalid, [data-qa="login-password"]:invalid',
	poloBrandLink: '.brands-name a[href="/brand_products/Polo"]',
	productsItems: '.features_items',
	productsTitle: '.title.text-center',
	productsBreadcrumbs: '.breadcrumbs',
	productsHeaderLink: '.shop-menu.pull-right a[href="/products"]',
	searchProductInput: '#search_product',
	searchProductButton: '#submit_search',
	viewProductLink: 'a[href^="/product_details/"]',
	addToCartButton: '.btn.btn-default.cart',
	viewCartLink: 'a[href="/view_cart"][title="View Cart"], a[href="/view_cart"]:contains("View Cart")',
	cartItems: '#cart_items',
	cartBreadcrumbs: '.breadcrumbs',
	cartAction: '#do_action',
	cartProduct: '.cart_product',
	cartDescription: '.cart_description',
	cartPrice: '.cart_price',
	cartQuantity: '.cart_quantity',
	cartTotal: '.cart_total',
	cartTotalPrice: '.cart_total_price',
	cartDelete: '.cart_delete',
	cartModal: '.modal-content',
	cartModalHeader: '.modal-header',
	cartModalBody: '.modal-body',
	cartModalFooter: '.modal-footer',
	cartModalText: '.text-center',
};

export default camposAutomationExercise;
