const camposAutomationExercise = {
	loginEmail: '[data-qa="login-email"]',
	loginPassword: '[data-qa="login-password"]',
	loginButton: '[data-qa="login-button"]',
	logoutLink: 'a[href="/logout"]',
	deleteAccountLink: 'a[href="/delete_account"]',
	userIcon: 'a:has(.fa.fa-user)',
	loginErrorMessage: 'p[style*="color: red"]',
	requiredLoginField: '[data-qa="login-email"]:invalid, [data-qa="login-password"]:invalid',
	poloBrandLink: '.brands-name a[href="/brand_products/Polo"]',
	productsItems: '.features_items',
	productsTitle: '.title.text-center',
	productsBreadcrumbs: '.breadcrumbs',
	productsHeaderLink: '.shop-menu.pull-right a[href="/products"]',
	searchProductInput: '#search_product',
	searchProductButton: '#submit_search',
	viewProductLink: 'a[href^="/product_details/"]',
	addToCartButton: '.btn.btn-default.cart',
	cartModal: '.modal-content',
	cartModalHeader: '.modal-header',
	cartModalBody: '.modal-body',
	cartModalFooter: '.modal-footer',
	cartModalText: '.text-center',
};

export default camposAutomationExercise;
