const camposCarrinho = {
	cartItems: '#cart_items',
	cartBreadcrumbs: '.breadcrumbs',
	cartAction: '#do_action',
	cartProduct: '.cart_product',
	cartDescription: '.cart_description',
	cartPrice: '.cart_price',
	cartQuantity: '.cart_quantity',
	cartTotal: '.cart_total',
	cartTotalPrice: '.cart_total_price',
	cartDelete: '.cart_delete',
	checkoutButton: '.btn.btn-default.check_out',
	checkoutCartItems: '#cart_items',
	checkoutBreadcrumbs: '.breadcrumbs',
	checkoutHeading: '.heading',
	checkoutInfo: '[data-qa="checkout-info"]',
	checkoutAddressBox: '.address.item.box',
	checkoutAddressTitle: '.address_title',
	checkoutAddressName: '.address_firstname.address_lastname',
	checkoutAddressStreet: '.address_address1.address_address2',
	checkoutAddressLocation: '.address_city.address_state_name.address_postcode',
	checkoutAddressCountry: '.address_country_name',
	checkoutAddressPhone: '.address_phone',
	checkoutAlternateAddressBox: '.address.alternate_item.box',
	checkoutAlternateTitle: '.address_title',
	checkoutAlternateName: '.address_firstname.address_lastname',
	checkoutAlternateStreet: '.address_address1.address_address2',
	checkoutAlternateLocation: '.address_city.address_state_name.address_postcode',
	checkoutAlternateCountry: '.address_country_name',
	checkoutAlternatePhone: '.address_phone',
};

export default camposCarrinho;
